//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Manager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marauder,0,5000,5,20,5000,10,0,30,heavy
        ///Vermin,1,50,10,2,1000,0,0,1,swarm
        ///.
        /// </summary>
        internal static string Enemies {
            get {
                return ResourceManager.GetString("Enemies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0:1
        ///1:5
        ///1:100
        ///1:60
        ///0:15
        ///.
        /// </summary>
        internal static string Levels {
            get {
                return ResourceManager.GetString("Levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1:10
        ///1:30
        ///1:100
        ///1:200
        ///1:500
        ///0:5
        ///0:30
        ///.
        /// </summary>
        internal static string Levels1 {
            get {
                return ResourceManager.GetString("Levels1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0:5
        ///1:20
        ///0:10
        ///1:100
        ///0:30
        ///1:300
        ///0:50
        ///1:500
        ///.
        /// </summary>
        internal static string Levels2 {
            get {
                return ResourceManager.GetString("Levels2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string Levels3 {
            get {
                return ResourceManager.GetString("Levels3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string Levels4 {
            get {
                return ResourceManager.GetString("Levels4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string Levels5 {
            get {
                return ResourceManager.GetString("Levels5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12
        ///GGGGGGGGGGGG
        ///GGGGGGGGGGGG
        ///GSPPPPPPPPGG
        ///GGTGGGTGGPGG
        ///GGGGGGPPPPGG
        ///GGGGGGPTGGGG
        ///GGGGGGPPPPTG
        ///GGGGGGGGGPGG
        ///GGTGGGGGTPGG
        ///GEPPPPPPPPGG
        ///GGGGGGGGGGGG
        ///GGGGGGGGGGGG
        ///
        ///3 2,3 6,5 7,6 10,8 2,8 8
        ///.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20
        ///GGGGGGGGGGGGGGGGGGGG
        ///GEPPPPGGGGTGGGGTPPPG
        ///GGGGGPGGGGTGGGGGPGPG
        ///GGGGGPTGGGGGGGTGPGPG
        ///GGGGGPPPPPPPPPPPPGPG
        ///GGTGGGGGGGGGGGGGGGPG
        ///GPPPPPPPPPPPPPPPPPPG
        ///GPGGGGGTGGGGGGGGGGGG
        ///GPGGGGGTGGGGGGGGGGGG
        ///GPPPPPPPPPPPPPPPPPPG
        ///GGGGTTGGGGGGGGGGGGPG
        ///GGGGGGGGGGGGGGGGTTPG
        ///GPPPPPPPPPPPPPPPPPPG
        ///GPGGGGGGGGGGGGTGGGGG
        ///GPGGTGGGGGGTGGGGGGGG
        ///GPPPPPPPPPPPPPPPPPPG
        ///GGGGGGGGGGGGGGGGTGPG
        ///GGGGGGGTGGGGTGGGGGPG
        ///GSPPPPPPPPPPPPPPPPPG
        ///GGGGGGGGGGGGGGGGGGGG.
        /// </summary>
        internal static string Map1 {
            get {
                return ResourceManager.GetString("Map1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19
        ///GGGGGGGGGGGGGGGGGG
        ///GGGGGGGGGGGGGGGGGG
        ///GGGSPPPPPPPPPPPPGG
        ///GGGGGGGGGGGGGGTPGG
        ///GGGGGGGGGGGGGGGPGG
        ///GGGPPPPPPPPPPGGPGG
        ///GGGPTGGGGGGTPGGPGG
        ///GGGPGGGGGGGGPGGPGG
        ///GGGPGGPPPPGGPGGPGG
        ///GGGPGGPTTPGGPGGPGG
        ///GGGPGGPGGEGGPGGPGG
        ///GGGPGGPGGGGGPGGPGG
        ///GGGPGGPTGGGTPGGPGG
        ///GGGPGGPPPPPPPGGPGG
        ///GGGPGGGGGGGGGGGPGG
        ///GGGPTGGGGGGGGGTPGG
        ///GGGPPPPPPPPPPPPPGG
        ///GGGGGGGGGGGGGGGGGG
        ///GGGGGGGGGGGGGGGGGG.
        /// </summary>
        internal static string Map2 {
            get {
                return ResourceManager.GetString("Map2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15
        ///GGGGGGGG
        ///GSGPPPEG
        ///GPTPGGGG
        ///GPTPGGGG
        ///GPGPPPPG
        ///GPGGGTPG
        ///GPGGGTPG
        ///GPGPPPPG
        ///GPTPGGGG
        ///GPTPGGGG
        ///GPGPPPPG
        ///GPGGGTPG
        ///GPGGGTPG
        ///GPPPPPPG
        ///GGGGGGGG.
        /// </summary>
        internal static string Map3 {
            get {
                return ResourceManager.GetString("Map3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5
        ///GGGGGGGGGGGGGGG
        ///GGGGGGGGTGTGTGG
        ///GSPPPPPPPPPPPEG
        ///GGGGGGGTGTGTGGG
        ///GGGGGGGGGGGGGGG.
        /// </summary>
        internal static string Map4 {
            get {
                return ResourceManager.GetString("Map4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6
        ///GGGGGGGGGGGGGGGGG
        ///GGPPPPPGGGPPPPPGG
        ///GGPGGGPPPPPGGGPGG
        ///GGPGGTGTTTGTGGPGG
        ///GGPPPPPEGSPPPPPGG
        ///GGGGGGGGGGGGGGGGG.
        /// </summary>
        internal static string Map5 {
            get {
                return ResourceManager.GetString("Map5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper,20,10,0,1000,20,500,0,0,0,0,0,25
        ///GrenadeThrower,20,10,0,24,8,300,0,0,0,1,50,25
        ///ArcaneMage,20,10,1,100,20,300,40,10,10,0,0,25
        ///.
        /// </summary>
        internal static string Towers {
            get {
                return ResourceManager.GetString("Towers", resourceCulture);
            }
        }
    }
}
