//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Manager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marauder,0,5000,5,20,1000,10,0,20
        ///Vermin,1,50,10,1,1,0,0,2
        ///.
        /// </summary>
        internal static string Enemies {
            get {
                return ResourceManager.GetString("Enemies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0:1
        ///1:1
        ///1:40
        ///1:60
        ///1:80
        ///.
        /// </summary>
        internal static string Levels {
            get {
                return ResourceManager.GetString("Levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12
        ///GGGGGGGGGGGG
        ///GGGGGGGGGGGG
        ///GSPPPPPPPPGG
        ///GGTGGGTGGPGG
        ///GGGGGGPPPPGG
        ///GGGGGGPTGGGG
        ///GGGGGGPPPPTG
        ///GGGGGGGGGPGG
        ///GGTGGGGGTPGG
        ///GEPPPPPPPPGG
        ///GGGGGGGGGGGG
        ///GGGGGGGGGGGG
        ///
        ///3 2,3 6,5 7,6 10,8 2,8 8
        ///.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper,20,10,0,1000,20,500,0,0,0,0,0,50
        ///GrenadeThrower,20,10,0,30,5,100,0,0,0,1,50,50
        ///ArcaneMage,20,10,1,100,20,200,40,10,10,0,0,50
        ///.
        /// </summary>
        internal static string Towers {
            get {
                return ResourceManager.GetString("Towers", resourceCulture);
            }
        }
    }
}
